# Numpy

In [ ]:
%pip install -q ipywidgets ipympl

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib widget

## Docs
https://numpy.org/doc/stable/reference/routines.html

Numpy is the defacto numerical library for python.

First things first, if you are using numpy like this:

In [ ]:
def bad_way(a, b):
    x = np.zeros(len(a))
    
    for i in range(len(a)):
        x[i] = 1.324 * a[i] - 12.99 * b[i] + 1
    
    return x

This is **BAD**, it does not take advantage of numpys greatest advantage. **Vectorization**

In [ ]:
def numpy_way(a, b):
    return 1.324 * a - 12.99 * b + 1

In [ ]:
a = np.arange(1e6)
b = np.arange(1e6)

We can see they are the same:

In [ ]:
np.all(numpy_way(a,b) == bad_way(a,b))

### But one is much faster:

In [ ]:
%timeit bad_way(a, b)

In [ ]:
%timeit numpy_way(a, b)

A preview into optimizations:

In [ ]:
a = np.random.rand(100,10,10,10,10)
b = np.random.rand(10,10,10,10,100)

In [ ]:
%timeit a[0,:,:,:,:] + 1

In [ ]:
%timeit a[:,:,:,:,0] + 1

We will discuss this tomorrow!

# Creating arrays

Creating arrays can be done using a python list or a tuple.

In [ ]:
a = np.array([10,20,30,40,50,60], dtype=np.float64)
a

### Array properties

In [ ]:
print(a.shape)
print(a.ndim)
print(a.nbytes)
print(a.dtype)

### Zeros

In [ ]:
a = np.zeros(10)
b = np.zeros(shape=(20, 10))

print(a)
print('-----')
print(b)

### Ones

In [ ]:
a = np.ones(10)
b = np.ones(shape=(5,2))

a,b

### Empty

In [ ]:
a = np.empty(10)
b = np.empty(shape=(5,2))

a,b

In [ ]:
c = np.zeros_like(b)
np.ones_like(c)

### Random Data

In [ ]:
x = np.random.randn(10,10)
x

### Create array between start and end with a sampling value

In [ ]:
a = np.arange(0, 10) # start, end, sampling
a

### Create array between start and end with a number of points

In [ ]:
a = np.linspace(0,10, 4) # start, end, number of points. 10 inclusive
a

In [ ]:
b = np.linspace(0, 10, 4, endpoint=False) # exclusive of 10
b

In [ ]:
c = np.logspace(-4, 4, 10)
c

### Create a ND mesh using 1D arrays

In [ ]:
x = np.linspace(-10, 10, 20)
y = np.linspace(-20, 20, 50)

X, Y = np.meshgrid(x,y)

print(X.shape)
print(Y.shape)




In [ ]:
fig, (ax1, ax2) = plt.subplots(1,2, figsize=(8,4))
ax1.set_title('X')
ax1.imshow(X)
ax2.set_title('Y')
ax2.imshow(Y)

# 

### Access tricks

Numpy has standard access with 0, 1, 2 but you can also access it **backwards** by using negative indices. For example `-1` will access the last element, `-2` the one before last etc.

In [ ]:
x = np.arange(0,10)
x

In [ ]:
x[0]

In [ ]:
x[1]

In [ ]:
x[-1]

In [ ]:
x[-2]

In [ ]:
x[-10]

## Slicing

### Slicing is one of numpys best features, you can manipulate arrays in interesting ways. 

Slicing is achieved using the `::` operator where the arguments are:
    
    [start index]:[end index]:skip
    
You can supply all, some, or none of the arguments

In [ ]:
# Load in some important data
data = np.loadtxt('../../data/important.txt')
plt.figure()
plt.imshow(data[::-2,::-1])
plt.show()

In [ ]:
figs, (ax1, ax2, ax3) = plt.subplots(1,3)
ax1.imshow(data[::2])
ax2.imshow(data[10:-1,::2])
ax3.imshow(data[4:50:2, 70:90:2])
figs.tight_layout()
plt.show()

### If we wanted a slice but only cared about the last axes we might end up doing this:

In [ ]:
def bad_many_slices_of_ham(array):
    if array.ndim == 2:
        return array[::2,::2]
    elif array.ndim == 3:
        return array[:, ::2, ::2]
    elif array.ndim == 4:
        return array[:, :, ::2, ::2]
    raise NotImplementedError
    

In [ ]:
bad_many_slices_of_ham(data.reshape(1,*data.shape))

In [ ]:
bad_many_slices_of_ham(data.reshape(1, 1,*data.shape))

In [ ]:
bad_many_slices_of_ham(data.reshape(1,1, 1,*data.shape))

### What we can do instead is exploit the ellipsis operator (...):

In [ ]:
def good_many_slices_of_ham(array):
    return array[..., ::2, ::2]

In [ ]:
good_many_slices_of_ham(data)

In [ ]:
good_many_slices_of_ham(data.reshape(1,1, 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,*data.shape))

In [ ]:
big_shape = data.reshape(1,1, 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,*data.shape)

In [ ]:
big_shape[::2, :, :, :, ..., ::4 ].shape

## Indexing and getting fancy filtering

In [ ]:
array = np.arange(0,400,4)
array

In [ ]:
array[[0, 50, 70]]

In [ ]:
v = np.arange(0,30,10, dtype=np.float64)
v.astype(np.int64)

In [ ]:
array[
    np.arange(0,30,10, dtype=np.float64).astype(np.int64)
]

## Filtering using boolean masks

If you perform a comparison of some kind (`==`, `<`, `>` etc). Numpy will generate a boolean array

In [ ]:
array < 50

In [ ]:
np.where(array < 50)

In [ ]:
mybool = np.array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, True, False, False, False, False,
       False], dtype=bool)

In [ ]:
array[np.where(mybool)]

In [ ]:
mybool.dtype

In [ ]:
array[mybool]

In [ ]:
array[ array < 10 ] = 0
array

### Exercise circular aperture

Given `x` and `y` coordinates and a `radius` create a `create_circle` function that produces an array of zeros with a circle of 1s
For example a function that works like this:

```python
    x = np.linspace(-10, 10, 5)
    y = np.linspace(-10, 10, 5)
    R = 5
    circle = create_circle(x, y, 5)
```
Would return an `circle` array like this:
```python
    [[0 0 0 0 0]
     [0 0 1 0 0]
     [0 1 1 1 0]
     [0 0 1 0 0]
     [0 0 0 0 0]]
```
Remember:
$$ 
R = \sqrt{x^2 + y^2} 
$$



In [ ]:
def create_circle(x, y, radius):
    pass

In [ ]:
x = np.linspace(-10, 10, 5)
y = np.linspace(-10, 10, 5)
R = 5
circle = create_circle(x, y, 5)

print(circle)

Now make an interact plot of it with an adjustable radius (You can refer to yesterdays notebook on this!)
You can use `plt` interface or if you're feeling fancy try `fig, ax` interface

In [ ]:
# Interactive plot here

### AND (&)

In [ ]:
print(True & True)
print(True & False)
print(False & False)

array[ (array <50) & (array > 20)]


### OR (|)

In [ ]:
print(True | True)
print(True | False)
print(False | False)

array[ (array <50) | (array > 350) ]

### Exclusive OR (^)

In [ ]:
print(True ^ True)
print(True ^ False)
print(False ^ False)

array[  (array < 50) ^ (array < 70)]

### NOT (~)

In [ ]:
print(not True)
print(not False)

In numpy not is represented by the (~) operator and is used like this:

In [ ]:
array[~(array >= 50)]

### Exercise build a square aperture

Like the circle aperture, using filtering given, `x`, `y`, `width` and `height` produce rectanglar aperture:

    >>> x = np.linspace(-10, 10, 5)
    >>> y = np.linspace(-10, 10, 5)
    >>> width = 5
    >>> height = 10
    >>> rect = create_rectangle(x, y, width, height)

Would return an `rectangle` array like this:
    
    [0 1 1 1 0]
    [0 1 1 1 0]
    [0 1 1 1 0]
    [0 1 1 1 0]
    [0 1 1 1 0]


Hint: You can use `np.abs` to take the absolute value

In [ ]:
def create_rectangle(x, y, width, height):
    pass

In [ ]:
plt.figure()
plt.imshow(create_rectangle(x, y, 5, 5))
plt.show()

In [ ]:
from ipywidgets.widgets import interact

x = np.linspace(-10, 10, 100)
y = np.linspace(-10, 10, 100)

# ...Do the plotting here
fig, ax = plt.subplots()

im = ax.imshow(create_rectangle(x,y,5, 10))

@interact(w=(0, 10,0.1), h=(0, 10, 0.1))
def update(w=5, h=5):
    new_rect = create_rectangle(x, y, w, h)
    im.set_data(new_rect)

## Broadcasting

Lets look at a common problem. We have a matrix `A` and a vector `x` and we want to apply `x` along the matrix. For example:
    
    A:
      [1,1,1,1]
      [1,1,1,1]
      [1,1,1,1]
    x:
      [1, 2, 3]
    
    result:
      [1,1,1,1]
      [2,2,2,2]
      [3,3,3,3]
How would we go about doing it?

In [ ]:
A = np.ones(shape=(3,4))
x = np.arange(1,4)
A,x

In [ ]:
A*x

We can insert a fake axis into `x` to make its shape "compatible" with `A`

In [ ]:
A*x[:, None]

Broadcasting allows you make arrays dimensionally compatible by inserting "fake" axis. Numpy determines compatible dimensions through two rules:

- they are equal, or
- one of them is 1

We can exploit this behavoir and build higher dimensional array operations using lower dimensional ones. For example, with just `x` and simulate an outer product

$\rvert x\rangle \langle x \rvert$

In [ ]:
x[:,None]*x[None,:]

In [ ]:
x[:,None] - x[None,:]

### Exercise Weins Law version II

Previously our Weins law function looked like this:

In [ ]:
def weins_law(wavelength, 
              temperature):

    h = 6.62607015e-34
    c = 299792458
    kB = 1.380e-23
    I0 = (2.0 * h * c ** 2) / wavelength ** 5
    
    return I0 * np.exp(-( h * c ) / ( wavelength * kB * temperature))

Now if we tried to pass in a temperature array and wavelength array what should the shape be?

In [ ]:
temperature = np.linspace(10,1000,100)
wavelength = np.linspace(0.1,100,100)

out = weins_law(wavelength, temperature)

In [ ]:
out.shape

Is this correct? What about if they're different shapes?


In [ ]:
temperature = np.linspace(10,1000,10)
wavelength = np.linspace(0.1,100,100)
out = weins_law(wavelength, temperature)

It doesn't, since for Weins law we expect:

- For *each* temperature we want all wavelengths
- The shape of the output array should be something like (Num T, Num wavelength)

Use broadcasting and fix our weins law function:

In [ ]:
def weins_law_II(wavelength, 
              temperature):
    pass

# (t, w)


temperature = np.linspace(10,1000,100)
wavelength = np.linspace(0.1,100,100)

out = weins_law_II(wavelength, temperature)

assert out.shape == (100,100)

temperature = np.linspace(10,1000,10)
wavelength = np.linspace(0.1,100,100)

out = weins_law_II(wavelength, temperature)

assert out.shape == (10,100)

In [ ]:
broad_out = out[:,None,:,None,None]
broad_out.shape

In [ ]:
broad_out.reshape(*out.shape).shape

In [ ]:
out.ravel().shape

## Linear Algebra

In [ ]:
A = np.arange(0, 100).reshape(10, 10)
v1 = np.arange(0, 10)

In [ ]:
v1.shape

### Matrix matrix

In [ ]:
np.dot(A,A)

In [ ]:
A @ A

### Matrix Vector

In [ ]:
np.dot(A, v1)

In [ ]:
A @ v1

### Dot product

In [ ]:
np.dot(v1, v1)

In [ ]:
v1 @ v1

In [ ]:
np.einsum('ij,jk -> i', A, A)

### Transpose

In [ ]:
np.random.rand(2,10).T.shape

### Complex

In [ ]:
A_complex = A*1j
A_complex.dtype

In [ ]:
v2 = np.array([5 + 1j, 4 + 4j])
print(v2.dtype)
v2

In [ ]:
v2.conjugate()

In [ ]:
v2*v2.conjugate()

In [ ]:
v2.imag

In [ ]:
print(v2.real)
v2.real[:] *= 2
print(v2.imag)
v2.imag[:] /= 2

v2


In [ ]:
np.abs(v1)

In [ ]:
np.sqrt(v2.real**2 + v2.imag**2)

### Matrix inverse

In [ ]:

A = np.random.rand(10,10)

np.linalg.inv(A)

In [ ]:
plt.figure()
plt.imshow(A @ np.linalg.inv(A))
plt.show()

### Matrix determinant

In [ ]:
np.linalg.det(A)

### Matrix eignvalues

In [ ]:
eignval, eignvec = np.linalg.eig(A)

In [ ]:
np.isclose(A @ eignvec, eignval*eignvec)

## Operations

### Reductions

In [ ]:
np.sum(A)
A.sum()

In [ ]:
A.shape

In [ ]:
A.sum(axis=0)

In [ ]:
A.sum(axis=1)

In [ ]:
B = np.random.rand(4,10)

B.sum(axis=1).shape

In [ ]:
np.mean(A), A.mean(), A.mean(axis=0)

In [ ]:
v1

In [ ]:
np.prod(v1 + 1)

In [ ]:
np.cumsum(v1)

In [ ]:
np.cumprod(v1 + 1)

In [ ]:
np.trace(A)

In [ ]:
np.diagonal(A).sum()

## Fourier Transform

Numpy provides the `fft` module which allows you to perform fourier transforms

In [ ]:
x = np.linspace(-np.pi, 10*np.pi, 1000)
plt.figure()
plt.plot(np.sin(x)*np.cos(2*x))
plt.show()

In [ ]:
out = np.fft.fft(np.sin(x)*np.cos(2*x))
plt.figure()
plt.plot(np.abs(out))
plt.show()

The output of the FFT can be a little strange, the first half are for frequencies between `0` and `N/2` and the second half is between `-N/2` and `0`, we can shift the zero to the centre using `fftshift`

In [ ]:
out = np.fft.fft(np.sin(x)*np.cos(2*x))
plt.figure()
plt.plot(np.absolute(np.fft.fftshift(out)))
plt.show()

We can also get the frequency coordinates using `fftfreq` (Remember to shift it as well!)

In [ ]:
np.fft.fftfreq?

In [ ]:
fx=np.fft.fftfreq(x.shape[0],d=x[1]-x[0])

fx = np.fft.fftshift(fx)
out = np.fft.fft(np.sin(x)*np.cos(2*x))

plt.figure()
plt.plot(fx, np.absolute(np.fft.fftshift(out)))
plt.show()

We can even do 2D FFTs. Lets try with our circle aperture function

In [ ]:
import matplotlib as mpl
x = np.linspace(-10,10,100)
y = np.linspace(-10,10,100)
r = 4.0

circle = create_circle(x, y, r)

fft_circle = np.fft.fftshift(np.fft.fft2(circle))

plt.figure()
im = plt.imshow(np.absolute(fft_circle), cmap='hot')

@interact(r=(0, 10,0.1))
def update(r=4):
    circle = create_circle(x, y, r)
    fft_circle = np.fft.fftshift(np.fft.fft2(circle))
    im.set_data(np.abs(fft_circle))
    


In [ ]:
import matplotlib as mpl
x = np.linspace(-10,10,100)
y = np.linspace(-10,10,100)
w = 2.0
h = 2.0

rectangle = create_rectangle(x, y, w, h)

fft_rect = np.fft.fftshift(np.fft.fft2(rectangle))

plt.figure()
im = plt.imshow(np.absolute(fft_rect), cmap='hot')

@interact(w=(0, 10,0.1), height=(0, 10, 0.1))
def update(w=2, h=2):
    rectangle = create_rectangle(x, y, w, h)
    fft_rect = np.fft.fftshift(np.fft.fft2(rectangle))
    im.set_data(np.abs(fft_rect))